package com.faltynka.faltynkaapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="Users")
public class Deck {

    private String id;
    private String name;
    private String userId;
    private Long limitNewPerDay;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "limitNewPerDay")
    public Long getLimitNewPerDay() { return limitNewPerDay;}

    public void setLimitNewPerDay(Long limitNewPerDay) {
        this.limitNewPerDay = limitNewPerDay;
    }

    public Deck(String name, String userId, Long limitNewPerDay) {
        this.name = name;
        this.userId = userId;
        this.limitNewPerDay = limitNewPerDay;
    }

    public Deck() {
    }


}
