package com.faltynka.faltynkaapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName="Vocabularies")
public class Vocabulary {

    private String id;
    private String deckId;
    private String front;
    private String back;
    private Long currentInterval;
    private boolean newVocabulary;
    private String nextLearnedAt;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "deckId-index")
    @DynamoDBAttribute(attributeName = "deckId")
    public String getDeckId() {
        return deckId;
    }

    public void setDeckId(String deckId) {
        this.deckId = deckId;
    }

    @DynamoDBAttribute(attributeName = "front")
    public String getFront() {
        return front;
    }

    public void setFront(String front) {
        this.front = front;
    }

    @DynamoDBAttribute(attributeName = "back")
    public String getBack() {return back; }

    public void setBack(String back) {
        this.back = back;
    }

    @DynamoDBAttribute(attributeName = "currentInterval")
    public Long getCurrentInterval() { return currentInterval;}

    public void setCurrentInterval(Long currentInterval) {
        this.currentInterval = currentInterval;
    }

    @DynamoDBAttribute(attributeName = "newVocabulary")
    public boolean isNewVocabulary() { return newVocabulary; }

    public void setNewVocabulary(boolean newVocabulary) {
        this.newVocabulary = newVocabulary;
    }

    @DynamoDBAttribute(attributeName = "nextLearnedAt")
    public String getNextLearnedAt() { return nextLearnedAt; }

    public void setNextLearnedAt(String nextLearnedAt) {
        this.nextLearnedAt = nextLearnedAt;
    }

    public Vocabulary(String deckId, String front, String back, Long currentInterval, boolean newVocabulary) {
        this.deckId = deckId;
        this.front = front;
        this.back = back;
        this.currentInterval = currentInterval;
        this.newVocabulary = newVocabulary;
    }

    public Vocabulary() {
    }


}
